pipelines:
  tags:
    v[0-9]*:
      - step:
          name: Build and publish
          image:
            name: sebduggan/commandbox-ci
            username: $DOCKER_HUB_USERNAME
            password: $DOCKER_HUB_PASSWORD
            email: $DOCKER_HUB_EMAIL
          caches:
            - node
          script:
            - ./build.sh
  branches:
    release-*:
      - step:
          name: Build and publish
          image:
            name: sebduggan/commandbox-ci
            username: $DOCKER_HUB_USERNAME
            password: $DOCKER_HUB_PASSWORD
            email: $DOCKER_HUB_EMAIL
          caches:
            - node
          script:
            - ./build.sh
